/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Wed Jun 21 19:33:47 CST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbMuxSimple.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbMuxSimple::MODEL_mkTbMuxSimple()
{
  mkTbMuxSimple_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbMuxSimple()
{
  MODEL_mkTbMuxSimple *model = new MODEL_mkTbMuxSimple();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbMuxSimple &INST_top = *((MOD_mkTbMuxSimple *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_test;
	 DEF_INST_top_DEF_CAN_FIRE_RL_test = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_test = DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_test)
	   INST_top.RL_test();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_cycle.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbMuxSimple::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbMuxSimple_instance = new MOD_mkTbMuxSimple(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbMuxSimple_instance->set_clk_0)("CLK");
}
void MODEL_mkTbMuxSimple::destroy_model()
{
  delete mkTbMuxSimple_instance;
  mkTbMuxSimple_instance = NULL;
}
void MODEL_mkTbMuxSimple::reset_model(bool asserted)
{
  (mkTbMuxSimple_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbMuxSimple::get_instance()
{
  return mkTbMuxSimple_instance;
}

/* Fill in version numbers */
void MODEL_mkTbMuxSimple::get_version(unsigned int *year,
				      unsigned int *month,
				      char const **annotation,
				      char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "14ff62d";
}

/* Get the model creation time */
time_t MODEL_mkTbMuxSimple::get_creation_time()
{
  
  /* Wed Jun 21 11:33:47 UTC 2023 */
  return 1687347227llu;
}

/* State dumping function */
void MODEL_mkTbMuxSimple::dump_state()
{
  (mkTbMuxSimple_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbMuxSimple & mkTbMuxSimple_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbMuxSimple *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbMuxSimple(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbMuxSimple::dump_VCD_defs()
{
  (mkTbMuxSimple_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbMuxSimple::dump_VCD(tVCDDumpType dt)
{
  (mkTbMuxSimple_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTbMuxSimple_backing(sim_hdl));
}
