/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Mon Jul 10 00:56:53 CST 2023
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbCFScheduling_h__
#define __mkTbCFScheduling_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbCFScheduling module */
class MOD_mkTbCFScheduling : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_m_cycle;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqBuf_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqBuf_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqBuf_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqBuf_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqBuf_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqBuf_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqBuf_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqPtr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqPtr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqPtr_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqPtr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_deqPtr_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqPtr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_deqPtr_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_ehr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_ehr_wires_2;
  MOD_Reg<tUInt32> INST_m_fifo_1_enqBuf_ehrReg;
  MOD_Wire<tUInt32> INST_m_fifo_1_enqBuf_ignored_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_1_enqBuf_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqBuf_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqBuf_virtual_reg_1;
  MOD_Wire<tUInt32> INST_m_fifo_1_enqBuf_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_1_enqBuf_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqPtr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqPtr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqPtr_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqPtr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_enqPtr_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqPtr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_enqPtr_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_nEmpty_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_nEmpty_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_nEmpty_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_nEmpty_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_nEmpty_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_nEmpty_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_nEmpty_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_nFull_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_1_nFull_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_nFull_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_nFull_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_nFull_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_1_nFull_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_1_nFull_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_regs_0;
  MOD_Reg<tUInt8> INST_m_fifo_1_regs_1;
  MOD_Reg<tUInt8> INST_m_fifo_1_regs_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqBuf_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqBuf_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqBuf_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqBuf_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqBuf_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqBuf_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqBuf_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqPtr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqPtr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqPtr_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqPtr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_deqPtr_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqPtr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_deqPtr_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_ehr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_ehr_wires_2;
  MOD_Reg<tUInt32> INST_m_fifo_2_enqBuf_ehrReg;
  MOD_Wire<tUInt32> INST_m_fifo_2_enqBuf_ignored_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_2_enqBuf_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqBuf_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqBuf_virtual_reg_1;
  MOD_Wire<tUInt32> INST_m_fifo_2_enqBuf_wires_0;
  MOD_Wire<tUInt32> INST_m_fifo_2_enqBuf_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqPtr_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqPtr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqPtr_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqPtr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_enqPtr_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqPtr_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_enqPtr_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_nEmpty_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_nEmpty_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_nEmpty_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_nEmpty_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_nEmpty_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_nEmpty_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_nEmpty_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_nFull_ehrReg;
  MOD_Wire<tUInt8> INST_m_fifo_2_nFull_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_nFull_ignored_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_nFull_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_nFull_virtual_reg_1;
  MOD_Wire<tUInt8> INST_m_fifo_2_nFull_wires_0;
  MOD_Wire<tUInt8> INST_m_fifo_2_nFull_wires_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_regs_0;
  MOD_Reg<tUInt8> INST_m_fifo_2_regs_1;
  MOD_Reg<tUInt8> INST_m_fifo_2_regs_2;
 
 /* Constructor */
 public:
  MOD_mkTbCFScheduling(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_stuff;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_stuff;
  tUInt8 DEF_WILL_FIRE_RL_m_clear_fifo_2;
  tUInt8 DEF_CAN_FIRE_RL_m_clear_fifo_2;
  tUInt8 DEF_WILL_FIRE_RL_m_enq_fifo_2;
  tUInt8 DEF_CAN_FIRE_RL_m_enq_fifo_2;
  tUInt8 DEF_WILL_FIRE_RL_m_deq_fifo_2;
  tUInt8 DEF_CAN_FIRE_RL_m_deq_fifo_2;
  tUInt8 DEF_WILL_FIRE_RL_m_clear_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_clear_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_deq_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_deq_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_enq_fifo_1;
  tUInt8 DEF_CAN_FIRE_RL_m_enq_fifo_1;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_nFull_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_nFull_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_nEmpty_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_nEmpty_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_enqBuf_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_enqBuf_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_deqBuf_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_deqBuf_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_deqPtr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_deqPtr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_2_enqPtr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_2_enqPtr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_nFull_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_nFull_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_nEmpty_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_nEmpty_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_enqBuf_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_enqBuf_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_deqBuf_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_deqBuf_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_deqPtr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_deqPtr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_fifo_1_enqPtr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_fifo_1_enqPtr_canonicalize;
 
 /* Local definitions */
 private:
  tUInt8 DEF_m_fifo_2_ehr_virtual_reg_2_read____d303;
  tUInt8 DEF_m_fifo_1_ehr_virtual_reg_2_read____d282;
  tUInt8 DEF_IF_m_fifo_2_deqBuf_wires_0_whas__48_THEN_m_fif_ETC___d151;
  tUInt8 DEF_IF_m_fifo_2_enqBuf_wires_0_whas__56_THEN_m_fif_ETC___d161;
  tUInt8 DEF_m_fifo_2_nEmpty_ehrReg__h13822;
  tUInt8 DEF_m_fifo_2_nFull_ehrReg__h14658;
  tUInt8 DEF_m_fifo_2_nEmpty_virtual_reg_1_read____d196;
  tUInt8 DEF_m_fifo_2_nEmpty_virtual_reg_0_read____d198;
  tUInt8 DEF_IF_m_fifo_1_enqBuf_wires_0_whas__5_THEN_m_fifo_ETC___d30;
  tUInt8 DEF_IF_m_fifo_1_deqBuf_wires_0_whas__7_THEN_m_fifo_ETC___d20;
  tUInt8 DEF_m_fifo_1_nEmpty_ehrReg__h4518;
  tUInt8 DEF_m_fifo_1_nFull_ehrReg__h5354;
  tUInt8 DEF_m_fifo_1_nEmpty_virtual_reg_1_read____d65;
  tUInt8 DEF_m_fifo_1_nEmpty_virtual_reg_0_read____d67;
  tUInt32 DEF_m_fifo_2_enqBuf_wires_0_wget____d157;
  tUInt32 DEF_m_fifo_2_enqBuf_ehrReg___d159;
  tUInt32 DEF_m_fifo_1_enqBuf_wires_0_wget____d26;
  tUInt32 DEF_m_fifo_1_enqBuf_ehrReg___d28;
  tUInt8 DEF_def__h25354;
  tUInt8 DEF_def__h23157;
  tUInt8 DEF_def__h24891;
  tUInt8 DEF_def__h24741;
  tUInt8 DEF_def__h22694;
  tUInt8 DEF_def__h22544;
  tUInt8 DEF_m_fifo_2_enqBuf_wires_0_whas____d156;
  tUInt8 DEF_m_fifo_2_deqBuf_wires_0_whas____d148;
  tUInt8 DEF_m_fifo_2_deqBuf_wires_0_wget____d149;
  tUInt8 DEF_m_fifo_2_deqBuf_ehrReg__h12050;
  tUInt8 DEF_m_fifo_1_enqBuf_wires_0_whas____d25;
  tUInt8 DEF_m_fifo_1_deqBuf_wires_0_whas____d17;
  tUInt8 DEF_m_fifo_1_deqBuf_wires_0_wget____d18;
  tUInt8 DEF_m_fifo_1_deqBuf_ehrReg__h2746;
  tUInt8 DEF_m_fifo_2_ehr_virtual_reg_1_read____d304;
  tUInt8 DEF_m_fifo_1_ehr_virtual_reg_1_read____d283;
  tUInt8 DEF_x__h13002;
  tUInt8 DEF_x__h13003;
  tUInt8 DEF_x__h3698;
  tUInt8 DEF_x__h3699;
  tUInt8 DEF_m_fifo_2_enqBuf_ehrReg_59_BIT_8___d160;
  tUInt8 DEF_m_fifo_2_enqBuf_wires_0_wget__57_BIT_8___d158;
  tUInt8 DEF_m_fifo_1_enqBuf_ehrReg_8_BIT_8___d29;
  tUInt8 DEF_m_fifo_1_enqBuf_wires_0_wget__6_BIT_8___d27;
  tUInt8 DEF_y__h17722;
  tUInt8 DEF_y__h8435;
  tUInt8 DEF_IF_m_fifo_2_enqBuf_wires_0_whas__56_THEN_m_fif_ETC___d171;
  tUInt8 DEF_IF_m_fifo_1_enqBuf_wires_0_whas__5_THEN_m_fifo_ETC___d40;
  tUInt8 DEF_IF_m_fifo_2_ehr_wires_0_whas__76_THEN_m_fifo_2_ETC___d279;
  tUInt8 DEF_IF_m_fifo_2_ehr_wires_1_whas__74_THEN_m_fifo_2_ETC___d280;
  tUInt8 DEF_IF_m_fifo_1_ehr_wires_0_whas__66_THEN_m_fifo_1_ETC___d269;
  tUInt8 DEF_IF_m_fifo_1_ehr_wires_1_whas__64_THEN_m_fifo_1_ETC___d270;
  tUInt8 DEF_x__h24864;
  tUInt8 DEF_x__h24714;
  tUInt8 DEF_x__h22667;
  tUInt8 DEF_x__h22517;
  tUInt8 DEF_IF_m_fifo_2_nFull_wires_0_whas__84_THEN_m_fifo_ETC___d187;
  tUInt8 DEF_IF_m_fifo_2_nEmpty_wires_0_whas__77_THEN_m_fif_ETC___d180;
  tUInt8 DEF_IF_m_fifo_1_nFull_wires_0_whas__3_THEN_m_fifo__ETC___d56;
  tUInt8 DEF_IF_m_fifo_1_nEmpty_wires_0_whas__6_THEN_m_fifo_ETC___d49;
  tUInt32 DEF__0_CONCAT_DONTCARE___d129;
  tUInt8 DEF_NOT_m_fifo_2_nFull_virtual_reg_1_read__03_04_A_ETC___d208;
  tUInt8 DEF_NOT_m_fifo_2_nEmpty_virtual_reg_1_read__96_97__ETC___d201;
  tUInt8 DEF_NOT_m_fifo_1_nEmpty_virtual_reg_1_read__5_6_AN_ETC___d70;
  tUInt8 DEF_NOT_m_fifo_1_nFull_virtual_reg_1_read__2_3_AND_ETC___d77;
 
 /* Rules */
 public:
  void RL_m_fifo_1_enqPtr_canonicalize();
  void RL_m_fifo_1_deqPtr_canonicalize();
  void RL_m_fifo_1_deqBuf_canonicalize();
  void RL_m_fifo_1_enqBuf_canonicalize();
  void RL_m_fifo_1_nEmpty_canonicalize();
  void RL_m_fifo_1_nFull_canonicalize();
  void RL_m_fifo_1_canonicalize();
  void RL_m_fifo_2_enqPtr_canonicalize();
  void RL_m_fifo_2_deqPtr_canonicalize();
  void RL_m_fifo_2_deqBuf_canonicalize();
  void RL_m_fifo_2_enqBuf_canonicalize();
  void RL_m_fifo_2_nEmpty_canonicalize();
  void RL_m_fifo_2_nFull_canonicalize();
  void RL_m_fifo_2_canonicalize();
  void RL_m_fifo_1_ehr_canonicalize();
  void RL_m_fifo_2_ehr_canonicalize();
  void RL_m_enq_fifo_1();
  void RL_m_deq_fifo_1();
  void RL_m_clear_fifo_1();
  void RL_m_deq_fifo_2();
  void RL_m_enq_fifo_2();
  void RL_m_clear_fifo_2();
  void RL_m_cycle_stuff();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbCFScheduling &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbCFScheduling &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbCFScheduling &backing);
};

#endif /* ifndef __mkTbCFScheduling_h__ */
