/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Wed Jun 28 14:06:51 CST 2023
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbPipelineFunctional_h__
#define __mkTbPipelineFunctional_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbPipelineFunctional module */
class MOD_mkTbPipelineFunctional : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_fifo_deqPtr_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_deqPtr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqPtr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_deqPtr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_deqPtr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_deqPtr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_deqPtr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_deqPtr_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqPtr_wires_1;
  MOD_Wire<tUInt8> INST_fifo_deqPtr_wires_2;
  MOD_Reg<tUInt8> INST_fifo_enqPtr_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_enqPtr_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_enqPtr_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_enqPtr_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_enqPtr_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_enqPtr_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_enqPtr_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_enqPtr_wires_0;
  MOD_Wire<tUInt8> INST_fifo_enqPtr_wires_1;
  MOD_Wire<tUInt8> INST_fifo_enqPtr_wires_2;
  MOD_Reg<tUInt8> INST_fifo_nEmpty_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_nEmpty_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_nEmpty_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_nEmpty_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_nEmpty_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_nEmpty_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_nEmpty_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_nEmpty_wires_0;
  MOD_Wire<tUInt8> INST_fifo_nEmpty_wires_1;
  MOD_Wire<tUInt8> INST_fifo_nEmpty_wires_2;
  MOD_Reg<tUInt8> INST_fifo_nFull_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_nFull_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_nFull_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_nFull_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_nFull_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_nFull_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_nFull_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_nFull_wires_0;
  MOD_Wire<tUInt8> INST_fifo_nFull_wires_1;
  MOD_Wire<tUInt8> INST_fifo_nFull_wires_2;
  MOD_Reg<tUInt8> INST_fifo_regs_0;
  MOD_Reg<tUInt8> INST_fifo_regs_1;
  MOD_Reg<tUInt8> INST_fifo_regs_2;
  MOD_Reg<tUInt32> INST_m_cycle;
  MOD_Reg<tUInt32> INST_m_input_count;
  MOD_Reg<tUInt32> INST_m_output_count;
  MOD_Wire<tUInt8> INST_m_randomA_ignore;
  MOD_Reg<tUInt8> INST_m_randomA_initialized;
  MOD_Wire<tUInt8> INST_m_randomA_zaz;
  MOD_Wire<tUInt8> INST_m_randomB_ignore;
  MOD_Reg<tUInt8> INST_m_randomB_initialized;
  MOD_Wire<tUInt8> INST_m_randomB_zaz;
  MOD_Wire<tUInt8> INST_m_randomC_ignore;
  MOD_Reg<tUInt8> INST_m_randomC_initialized;
  MOD_Wire<tUInt8> INST_m_randomC_zaz;
  MOD_Wire<tUInt8> INST_m_randomData_ignore;
  MOD_Reg<tUInt8> INST_m_randomData_initialized;
  MOD_Wire<tUInt8> INST_m_randomData_zaz;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_ehrReg;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_2;
  MOD_Reg<tUInt32> INST_m_ref_fifo_fake_pipeline_fifo_ehrReg;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ehrReg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ehrReg_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ehrReg_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ehrReg_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_0_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_0_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_0_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_0_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_1_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_1_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_1_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_1_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ignored_wires_2_1;
  MOD_Fifo<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_ref_noncf_fifo;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_0_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_0_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_0_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_0_4;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_1_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_1_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_1_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_1_4;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_virtual_reg_2_1;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_pipeline_fifo_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_0_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_0_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_0_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_0_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_pipeline_fifo_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_1_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_1_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_1_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_1_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_pipeline_fifo_wires_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_pipeline_fifo_wires_2_1;
 
 /* Constructor */
 public:
  MOD_mkTbPipelineFunctional(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_WILL_FIRE_RL_m_stop_tb;
  tUInt8 DEF_CAN_FIRE_RL_m_stop_tb;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_WILL_FIRE_RL_m_maybe_clear;
  tUInt8 DEF_CAN_FIRE_RL_m_maybe_clear;
  tUInt8 DEF_WILL_FIRE_RL_m_check_outputs;
  tUInt8 DEF_CAN_FIRE_RL_m_check_outputs;
  tUInt8 DEF_WILL_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_CAN_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_WILL_FIRE_RL_m_init;
  tUInt8 DEF_CAN_FIRE_RL_m_init;
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_print;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_print;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_post_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_post_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_pre_canonicalize_two;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_pre_canonicalize_two;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_pre_canonicalize_one;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_pre_canonicalize_one;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_4;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_4;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_3;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_3;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_2;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_2;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_1;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_1;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_pipeline_fifo_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_nFull_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_nFull_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_nEmpty_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_nEmpty_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_deqPtr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_deqPtr_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_enqPtr_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_enqPtr_canonicalize;
  tUInt8 DEF_fifo_nEmpty_virtual_reg_2_read__48_OR_fifo_nEm_ETC___d305;
  tUInt8 DEF_fifo_nEmpty_ehrReg__h3517;
  tUInt8 DEF_fifo_nEmpty_virtual_reg_2_read____d248;
  tUInt8 DEF_fifo_nEmpty_virtual_reg_1_read____d250;
  tUInt8 DEF_fifo_nEmpty_virtual_reg_0_read____d252;
  tUInt8 DEF_IF_fifo_nFull_wires_0_whas__5_THEN_fifo_nFull__ETC___d38;
  tUInt8 DEF_fifo_nFull_virtual_reg_2_read____d200;
  tUInt8 DEF_fifo_nFull_virtual_reg_1_read____d202;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_virtual_reg_1_read____d127;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_virtual_reg_2_read____d126;
  tUInt32 DEF_x__h21469;
  tUInt32 DEF_x__h21617;
  tUInt32 DEF_m_ref_fifo_fake_pipeline_fifo_wires_0_wget____d48;
  tUInt32 DEF_m_ref_fifo_fake_pipeline_fifo_ehrReg___d50;
  tUInt8 DEF_def__h21130;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_wires_0_1_wget____d78;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_ehrReg_1___d80;
  tUInt8 DEF_x_wget__h14179;
  tUInt8 DEF_x_wget__h13790;
  tUInt8 DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d194;
  tUInt8 DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d195;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_ehrReg_4__h9801;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_ehrReg_3__h8965;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_virtual_reg_2_1__ETC___d132;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_virtual_reg_1_1__ETC___d133;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_wires_0_1_whas____d77;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_wires_0_whas____d47;
  tUInt8 DEF_fifo_nFull_wires_0_whas____d35;
  tUInt8 DEF_fifo_nFull_wires_0_wget____d36;
  tUInt8 DEF_fifo_nFull_ehrReg__h4640;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_ehrReg_0_BIT_8___d51;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_wires_0_wget__8__ETC___d49;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_ehrReg_1_0_BIT_1___d81;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_wires_0_1_wget___ETC___d79;
  tUInt8 DEF_n__read__h19532;
  tUInt8 DEF_n__read__h17833;
  tUInt8 DEF_IF_m_ref_fifo_elem_count_wires_0_whas__57_THEN_ETC___d160;
  tUInt8 DEF_v__h14316;
  tUInt8 DEF_v__h13927;
  tUInt8 DEF_IF_m_ref_fifo_fake_pipeline_fifo_wires_0_4_wha_ETC___d120;
  tUInt8 DEF_IF_m_ref_fifo_fake_pipeline_fifo_wires_0_3_wha_ETC___d113;
  tUInt8 DEF_m_input_count_14_EQ_1024___d313;
  tUInt8 DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__9_ETC___d246;
  tUInt8 DEF_IF_m_randomB_zaz_whas__74_THEN_m_randomB_zaz_w_ETC___d241;
  tUInt8 DEF_IF_m_randomA_zaz_whas__67_THEN_m_randomA_zaz_w_ETC___d193;
  tUInt8 DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d247;
  tUInt8 DEF_NOT_fifo_nEmpty_virtual_reg_2_read__48_49_AND__ETC___d256;
  tUInt8 DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d199;
  tUInt8 DEF_NOT_fifo_nFull_virtual_reg_2_read__00_01_AND_N_ETC___d205;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h16187;
  tUInt32 DEF_v__h15013;
  tUInt32 DEF_v__h14623;
  tUInt32 DEF_v__h14236;
  tUInt32 DEF_v__h13847;
  tUInt32 DEF_x__h20180;
  tUInt8 DEF_def__h20062;
  tUInt8 DEF_x_wget__h14956;
  tUInt8 DEF__read__h250;
  tUInt8 DEF__read__h219;
  tUInt8 DEF__read__h188;
  tUInt8 DEF_x_wget__h14566;
  tUInt8 DEF_def__h20559;
  tUInt8 DEF_def__h20382;
  tUInt8 DEF_fifo_deqPtr_virtual_reg_2_read____d230;
  tUInt8 DEF_fifo_deqPtr_virtual_reg_1_read____d231;
  tUInt8 DEF_x__h6047;
  tUInt8 DEF_x__h6048;
  tUInt8 DEF_m_ref_fifo_fake_pipeline_fifo_ehrReg_1_0_BIT_0___d95;
  tUInt8 DEF_b__h18610;
  tUInt8 DEF_n__read__h18861;
  tUInt8 DEF_x_first__h13490;
  tUInt8 DEF_IF_m_ref_fifo_fake_pipeline_fifo_wires_0_2_wha_ETC___d106;
  tUInt8 DEF_v__h15093;
  tUInt8 DEF_IF_m_ref_fifo_fake_pipeline_fifo_wires_0_whas__ETC___d66;
  tUInt8 DEF_v__h14703;
  tUInt8 DEF_IF_fifo_deqPtr_wires_0_whas__5_THEN_fifo_deqPt_ETC___d18;
  tUInt8 DEF_IF_fifo_enqPtr_wires_0_whas_THEN_fifo_enqPtr_w_ETC___d8;
  tUInt8 DEF_x__h21083;
  tUInt8 DEF_x__h20512;
  tUInt8 DEF_x__h20335;
  tUInt8 DEF_IF_m_ref_fifo_fake_pipeline_fifo_wires_0_1_wha_ETC___d96;
  tUInt8 DEF_IF_m_ref_fifo_fake_pipeline_fifo_wires_0_1_wha_ETC___d82;
  tUInt8 DEF_IF_m_ref_fifo_fake_pipeline_fifo_wires_0_whas__ETC___d52;
  tUInt8 DEF_IF_fifo_nFull_wires_1_whas__3_THEN_fifo_nFull__ETC___d39;
  tUInt8 DEF_IF_fifo_nEmpty_wires_1_whas__3_THEN_fifo_nEmpt_ETC___d29;
  tUInt8 DEF_IF_fifo_nEmpty_wires_0_whas__5_THEN_fifo_nEmpt_ETC___d28;
 
 /* Rules */
 public:
  void RL_fifo_enqPtr_canonicalize();
  void RL_fifo_deqPtr_canonicalize();
  void RL_fifo_nEmpty_canonicalize();
  void RL_fifo_nFull_canonicalize();
  void RL_m_ref_fifo_fake_pipeline_fifo_canonicalize();
  void RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_1();
  void RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_2();
  void RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_3();
  void RL_m_ref_fifo_fake_pipeline_fifo_canonicalize_4();
  void RL_m_ref_fifo_fake_pipeline_fifo_pre_canonicalize_one();
  void RL_m_ref_fifo_fake_pipeline_fifo_pre_canonicalize_two();
  void RL_m_ref_fifo_fake_pipeline_fifo_post_canonicalize();
  void RL_m_ref_fifo_elem_count_canonicalize();
  void RL_m_randomA_every();
  void RL_m_randomA_every_1();
  void RL_m_randomB_every();
  void RL_m_randomB_every_1();
  void RL_m_randomC_every();
  void RL_m_randomC_every_1();
  void RL_m_randomData_every();
  void RL_m_randomData_every_1();
  void RL_m_cycle_print();
  void RL_m_init();
  void RL_m_feed_inputs();
  void RL_m_check_outputs();
  void RL_m_maybe_clear();
  void RL_m_check_fifos_not_full();
  void RL_m_check_fifos_not_empty();
  void RL_m_check_fifos_first();
  void RL_m_stop_tb();
  void RL_m_cycle_inc();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbPipelineFunctional &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbPipelineFunctional &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbPipelineFunctional &backing);
};

#endif /* ifndef __mkTbPipelineFunctional_h__ */
