/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Mon Jul 10 00:56:52 CST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbCFFunctional.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbCFFunctional::MODEL_mkTbCFFunctional()
{
  mkTbCFFunctional_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbCFFunctional()
{
  MODEL_mkTbCFFunctional *model = new MODEL_mkTbCFFunctional();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbCFFunctional &INST_top = *((MOD_mkTbCFFunctional *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_m_randomA_initialized__h17559;
	 tUInt8 DEF_INST_top_DEF_m_randomB_initialized__h17948;
	 tUInt8 DEF_INST_top_DEF_m_randomData_initialized__h18725;
	 tUInt8 DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d215;
	 tUInt8 DEF_INST_top_DEF_m_randomC_initialized__h18335;
	 INST_top.DEF_CAN_FIRE_RL_fifo_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_deqBuf_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_deqBuf_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_deqBuf_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_deqPtr_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_deqPtr_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_deqPtr_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_enqBuf_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_enqBuf_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_enqBuf_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_enqPtr_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_enqPtr_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_enqPtr_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_nEmpty_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_nEmpty_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_nEmpty_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_nFull_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_nFull_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_nFull_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_inc = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_inc = INST_top.DEF_CAN_FIRE_RL_m_cycle_inc;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_print = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_print = INST_top.DEF_CAN_FIRE_RL_m_cycle_print;
	 INST_top.DEF_x__h21277 = INST_top.INST_m_cycle.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_init = (INST_top.DEF_x__h21277) == 0u;
	 INST_top.DEF_WILL_FIRE_RL_m_init = INST_top.DEF_CAN_FIRE_RL_m_init;
	 DEF_INST_top_DEF_m_randomC_initialized__h18335 = INST_top.INST_m_randomC_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_maybe_clear = DEF_INST_top_DEF_m_randomC_initialized__h18335;
	 INST_top.DEF_WILL_FIRE_RL_m_maybe_clear = INST_top.DEF_CAN_FIRE_RL_m_maybe_clear;
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every = INST_top.DEF_CAN_FIRE_RL_m_randomA_every;
	 DEF_INST_top_DEF_m_randomA_initialized__h17559 = INST_top.INST_m_randomA_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1 = !DEF_INST_top_DEF_m_randomA_initialized__h17559;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1;
	 DEF_INST_top_DEF_m_randomB_initialized__h17948 = INST_top.INST_m_randomB_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1 = !DEF_INST_top_DEF_m_randomB_initialized__h17948;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every = INST_top.DEF_CAN_FIRE_RL_m_randomB_every;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every = INST_top.DEF_CAN_FIRE_RL_m_randomC_every;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1 = !DEF_INST_top_DEF_m_randomC_initialized__h18335;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1;
	 DEF_INST_top_DEF_m_randomData_initialized__h18725 = INST_top.INST_m_randomData_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1 = !DEF_INST_top_DEF_m_randomData_initialized__h18725;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every = INST_top.DEF_CAN_FIRE_RL_m_randomData_every;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_1 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_1;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_2 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_2 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_2;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_3 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_3 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_3;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_4 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_4 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_4;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_one = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_one = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_one;
	 DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d215 = INST_top.INST_m_ref_fifo_ref_noncf_fifo.METH_i_notEmpty();
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_two = DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d215;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_two = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_two;
	 INST_top.DEF_x__h21129 = INST_top.INST_m_input_count.METH_read();
	 INST_top.DEF_m_input_count_81_EQ_1024___d329 = (INST_top.DEF_x__h21129) == 1024u;
	 INST_top.DEF_CAN_FIRE_RL_m_stop_tb = INST_top.DEF_m_input_count_81_EQ_1024___d329 || (INST_top.DEF_x__h21277) == 4096u;
	 INST_top.DEF_WILL_FIRE_RL_m_stop_tb = INST_top.DEF_CAN_FIRE_RL_m_stop_tb;
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_print)
	   INST_top.RL_m_cycle_print();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_one)
	   INST_top.RL_m_ref_fifo_pre_canonicalize_one();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_two)
	   INST_top.RL_m_ref_fifo_pre_canonicalize_two();
	 if (INST_top.DEF_WILL_FIRE_RL_m_stop_tb)
	   INST_top.RL_m_stop_tb();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full)
	   INST_top.RL_m_check_fifos_not_full();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty)
	   INST_top.RL_m_check_fifos_not_empty();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first)
	   INST_top.RL_m_check_fifos_first();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every)
	   INST_top.RL_m_randomA_every();
	 INST_top.DEF_fifo_nFull_ehrReg__h5305 = INST_top.INST_fifo_nFull_ehrReg.METH_read();
	 INST_top.DEF_fifo_nFull_virtual_reg_1_read____d72 = INST_top.INST_fifo_nFull_virtual_reg_1.METH_read();
	 INST_top.DEF_fifo_nFull_virtual_reg_0_read____d74 = INST_top.INST_fifo_nFull_virtual_reg_0.METH_read();
	 INST_top.DEF_x_wget__h17428 = INST_top.INST_m_randomA_zaz.METH_wget();
	 INST_top.DEF_m_ref_fifo_ehrReg_3__h13720 = INST_top.INST_m_ref_fifo_ehrReg_3.METH_read();
	 INST_top.DEF_v__h17565 = INST_top.INST_m_randomA_zaz.METH_whas() ? INST_top.DEF_x_wget__h17428 : (tUInt8)0u;
	 INST_top.DEF_IF_m_ref_fifo_wires_0_3_whas__01_THEN_m_ref_fi_ETC___d204 = INST_top.INST_m_ref_fifo_wires_0_3.METH_whas() ? INST_top.INST_m_ref_fifo_wires_0_3.METH_wget() : INST_top.DEF_m_ref_fifo_ehrReg_3__h13720;
	 INST_top.DEF_IF_m_randomA_zaz_whas__47_THEN_m_randomA_zaz_w_ETC___d273 = (INST_top.DEF_v__h17565) == (tUInt8)0u;
	 INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_3_read__74_75_AND_ETC___d276 = !INST_top.INST_m_ref_fifo_virtual_reg_1_3.METH_read() && INST_top.DEF_IF_m_ref_fifo_wires_0_3_whas__01_THEN_m_ref_fi_ETC___d204;
	 INST_top.DEF_NOT_fifo_nFull_virtual_reg_1_read__2_3_AND_NOT_ETC___d77 = !(INST_top.DEF_fifo_nFull_virtual_reg_1_read____d72) && (!(INST_top.DEF_fifo_nFull_virtual_reg_0_read____d74) && INST_top.DEF_fifo_nFull_ehrReg__h5305);
	 INST_top.DEF_CAN_FIRE_RL_m_feed_inputs = (DEF_INST_top_DEF_m_randomA_initialized__h17559 && (INST_top.DEF_IF_m_randomA_zaz_whas__47_THEN_m_randomA_zaz_w_ETC___d273 || (INST_top.DEF_NOT_fifo_nFull_virtual_reg_1_read__2_3_AND_NOT_ETC___d77 && (DEF_INST_top_DEF_m_randomData_initialized__h18725 && INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_3_read__74_75_AND_ETC___d276)))) && (INST_top.DEF_x__h21129) < 1024u;
	 INST_top.DEF_WILL_FIRE_RL_m_feed_inputs = INST_top.DEF_CAN_FIRE_RL_m_feed_inputs;
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1)
	   INST_top.RL_m_randomA_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every)
	   INST_top.RL_m_randomB_every();
	 INST_top.DEF_fifo_nEmpty_ehrReg__h4469 = INST_top.INST_fifo_nEmpty_ehrReg.METH_read();
	 INST_top.DEF_fifo_nEmpty_virtual_reg_1_read____d65 = INST_top.INST_fifo_nEmpty_virtual_reg_1.METH_read();
	 INST_top.DEF_fifo_nEmpty_virtual_reg_0_read____d67 = INST_top.INST_fifo_nEmpty_virtual_reg_0.METH_read();
	 INST_top.DEF_x_wget__h17817 = INST_top.INST_m_randomB_zaz.METH_wget();
	 INST_top.DEF_m_ref_fifo_ehrReg_4__h14556 = INST_top.INST_m_ref_fifo_ehrReg_4.METH_read();
	 INST_top.DEF_v__h17954 = INST_top.INST_m_randomB_zaz.METH_whas() ? INST_top.DEF_x_wget__h17817 : (tUInt8)0u;
	 INST_top.DEF_IF_m_ref_fifo_wires_0_4_whas__08_THEN_m_ref_fi_ETC___d211 = INST_top.INST_m_ref_fifo_wires_0_4.METH_whas() ? INST_top.INST_m_ref_fifo_wires_0_4.METH_wget() : INST_top.DEF_m_ref_fifo_ehrReg_4__h14556;
	 INST_top.DEF_IF_m_randomB_zaz_whas__54_THEN_m_randomB_zaz_w_ETC___d291 = (INST_top.DEF_v__h17954) == (tUInt8)0u;
	 INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_4_read__92_93_AND_ETC___d294 = !INST_top.INST_m_ref_fifo_virtual_reg_1_4.METH_read() && INST_top.DEF_IF_m_ref_fifo_wires_0_4_whas__08_THEN_m_ref_fi_ETC___d211;
	 INST_top.DEF_NOT_fifo_nEmpty_virtual_reg_1_read__5_6_AND_NO_ETC___d70 = !(INST_top.DEF_fifo_nEmpty_virtual_reg_1_read____d65) && (!(INST_top.DEF_fifo_nEmpty_virtual_reg_0_read____d67) && INST_top.DEF_fifo_nEmpty_ehrReg__h4469);
	 INST_top.DEF_CAN_FIRE_RL_m_check_outputs = DEF_INST_top_DEF_m_randomB_initialized__h17948 && (INST_top.DEF_IF_m_randomB_zaz_whas__54_THEN_m_randomB_zaz_w_ETC___d291 || (INST_top.DEF_NOT_fifo_nEmpty_virtual_reg_1_read__5_6_AND_NO_ETC___d70 && INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_4_read__92_93_AND_ETC___d294));
	 INST_top.DEF_WILL_FIRE_RL_m_check_outputs = INST_top.DEF_CAN_FIRE_RL_m_check_outputs;
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_outputs)
	   INST_top.RL_m_check_outputs();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1)
	   INST_top.RL_m_randomB_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every)
	   INST_top.RL_m_randomC_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1)
	   INST_top.RL_m_randomC_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every)
	   INST_top.RL_m_randomData_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_feed_inputs)
	   INST_top.RL_m_feed_inputs();
	 INST_top.DEF_m_ref_fifo_virtual_reg_2_read____d217 = INST_top.INST_m_ref_fifo_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_virtual_reg_1_read____d218 = INST_top.INST_m_ref_fifo_virtual_reg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_wires_0_wget____d139 = INST_top.INST_m_ref_fifo_wires_0.METH_wget();
	 INST_top.DEF_m_ref_fifo_wires_0_1_wget____d169 = INST_top.INST_m_ref_fifo_wires_0_1.METH_wget();
	 INST_top.DEF_m_ref_fifo_ehrReg___d141 = INST_top.INST_m_ref_fifo_ehrReg.METH_read();
	 INST_top.DEF_m_ref_fifo_ehrReg_1___d171 = INST_top.INST_m_ref_fifo_ehrReg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_virtual_reg_2_1_read____d223 = INST_top.INST_m_ref_fifo_virtual_reg_2_1.METH_read();
	 INST_top.DEF_m_ref_fifo_virtual_reg_1_1_read____d224 = INST_top.INST_m_ref_fifo_virtual_reg_1_1.METH_read();
	 INST_top.DEF_m_ref_fifo_wires_0_1_whas____d168 = INST_top.INST_m_ref_fifo_wires_0_1.METH_whas();
	 INST_top.DEF_m_ref_fifo_wires_0_whas____d138 = INST_top.INST_m_ref_fifo_wires_0.METH_whas();
	 INST_top.DEF_m_ref_fifo_ehrReg_41_BIT_8___d142 = (tUInt8)((INST_top.DEF_m_ref_fifo_ehrReg___d141) >> 8u);
	 INST_top.DEF_m_ref_fifo_wires_0_wget__39_BIT_8___d140 = (tUInt8)((INST_top.DEF_m_ref_fifo_wires_0_wget____d139) >> 8u);
	 INST_top.DEF_m_ref_fifo_ehrReg_1_71_BIT_1___d172 = (tUInt8)((INST_top.DEF_m_ref_fifo_ehrReg_1___d171) >> 1u);
	 INST_top.DEF_m_ref_fifo_wires_0_1_wget__69_BIT_1___d170 = (tUInt8)((INST_top.DEF_m_ref_fifo_wires_0_1_wget____d169) >> 1u);
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_post_canonicalize = ((INST_top.DEF_m_ref_fifo_virtual_reg_2_read____d217 || (INST_top.DEF_m_ref_fifo_virtual_reg_1_read____d218 || (INST_top.DEF_m_ref_fifo_wires_0_whas____d138 ? !(INST_top.DEF_m_ref_fifo_wires_0_wget__39_BIT_8___d140) : !(INST_top.DEF_m_ref_fifo_ehrReg_41_BIT_8___d142)))) || INST_top.INST_m_ref_fifo_ref_noncf_fifo.METH_i_notFull()) && ((INST_top.DEF_m_ref_fifo_virtual_reg_2_1_read____d223 || (INST_top.DEF_m_ref_fifo_virtual_reg_1_1_read____d224 || (INST_top.DEF_m_ref_fifo_wires_0_1_whas____d168 ? !(INST_top.DEF_m_ref_fifo_wires_0_1_wget__69_BIT_1___d170) : !(INST_top.DEF_m_ref_fifo_ehrReg_1_71_BIT_1___d172)))) || DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d215);
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_post_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_post_canonicalize;
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_canonicalize)
	   INST_top.RL_fifo_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_deqBuf_canonicalize)
	   INST_top.RL_fifo_deqBuf_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_enqBuf_canonicalize)
	   INST_top.RL_fifo_enqBuf_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1)
	   INST_top.RL_m_randomData_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_2)
	   INST_top.RL_m_ref_fifo_canonicalize_2();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_3)
	   INST_top.RL_m_ref_fifo_canonicalize_3();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_4)
	   INST_top.RL_m_ref_fifo_canonicalize_4();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_post_canonicalize)
	   INST_top.RL_m_ref_fifo_post_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_maybe_clear)
	   INST_top.RL_m_maybe_clear();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_deqPtr_canonicalize)
	   INST_top.RL_fifo_deqPtr_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_enqPtr_canonicalize)
	   INST_top.RL_fifo_enqPtr_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_nEmpty_canonicalize)
	   INST_top.RL_fifo_nEmpty_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_nFull_canonicalize)
	   INST_top.RL_fifo_nFull_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_init)
	   INST_top.RL_m_init();
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_inc)
	   INST_top.RL_m_cycle_inc();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize)
	   INST_top.RL_m_ref_fifo_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_1)
	   INST_top.RL_m_ref_fifo_canonicalize_1();
	 INST_top.INST_m_randomData_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomData_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqBuf_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqBuf_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqBuf_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqBuf_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqBuf_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqBuf_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqBuf_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqBuf_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_fifo_regs_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_regs_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_regs_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_enqPtr_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_deqPtr_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_deqBuf_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_enqBuf_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_nEmpty_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_nFull_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ref_noncf_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_cycle.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_input_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_output_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomA_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomB_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomC_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomData_initialized.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbCFFunctional::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbCFFunctional_instance = new MOD_mkTbCFFunctional(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbCFFunctional_instance->INST_fifo_enqPtr_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_enqPtr_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_enqPtr_ignored_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_enqPtr_ignored_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqPtr_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqPtr_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqPtr_ignored_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqPtr_ignored_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqBuf_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqBuf_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqBuf_ignored_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_deqBuf_ignored_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_enqBuf_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_enqBuf_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_enqBuf_ignored_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_enqBuf_ignored_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nEmpty_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nEmpty_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nEmpty_ignored_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nEmpty_ignored_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nFull_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nFull_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nFull_ignored_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_fifo_nFull_ignored_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ref_noncf_fifo.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_2.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_0.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_2.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_0_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_1_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_2_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_0_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_1_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_2_1.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_0_2.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_1_2.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_0_2.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_1_2.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_0_3.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_1_3.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_0_3.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_1_3.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_0_4.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_wires_1_4.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_0_4.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_ref_fifo_ignored_wires_1_4.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomA_ignore.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomA_zaz.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomB_ignore.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomB_zaz.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomC_ignore.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomC_zaz.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomData_ignore.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->INST_m_randomData_zaz.set_clk_0)("CLK");
  (mkTbCFFunctional_instance->set_clk_0)("CLK");
}
void MODEL_mkTbCFFunctional::destroy_model()
{
  delete mkTbCFFunctional_instance;
  mkTbCFFunctional_instance = NULL;
}
void MODEL_mkTbCFFunctional::reset_model(bool asserted)
{
  (mkTbCFFunctional_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbCFFunctional::get_instance()
{
  return mkTbCFFunctional_instance;
}

/* Fill in version numbers */
void MODEL_mkTbCFFunctional::get_version(unsigned int *year,
					 unsigned int *month,
					 char const **annotation,
					 char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "14ff62d";
}

/* Get the model creation time */
time_t MODEL_mkTbCFFunctional::get_creation_time()
{
  
  /* Sun Jul  9 16:56:52 UTC 2023 */
  return 1688921812llu;
}

/* State dumping function */
void MODEL_mkTbCFFunctional::dump_state()
{
  (mkTbCFFunctional_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbCFFunctional & mkTbCFFunctional_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbCFFunctional *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbCFFunctional(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbCFFunctional::dump_VCD_defs()
{
  (mkTbCFFunctional_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbCFFunctional::dump_VCD(tVCDDumpType dt)
{
  (mkTbCFFunctional_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTbCFFunctional_backing(sim_hdl));
}
