/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Wed Jun 28 21:40:04 CST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbBypassFunctional.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbBypassFunctional::MODEL_mkTbBypassFunctional()
{
  mkTbBypassFunctional_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbBypassFunctional()
{
  MODEL_mkTbBypassFunctional *model = new MODEL_mkTbBypassFunctional();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbBypassFunctional &INST_top = *((MOD_mkTbBypassFunctional *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d306;
	 tUInt8 DEF_INST_top_DEF_m_randomA_initialized__h16152;
	 tUInt8 DEF_INST_top_DEF_m_randomB_initialized__h16541;
	 tUInt8 DEF_INST_top_DEF_m_randomData_initialized__h17318;
	 tUInt8 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d124;
	 tUInt8 DEF_INST_top_DEF_m_randomC_initialized__h16928;
	 INST_top.DEF_CAN_FIRE_RL_fifo_deqPtr_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_deqPtr_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_deqPtr_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_enqPtr_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_enqPtr_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_enqPtr_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_nEmpty_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_nEmpty_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_nEmpty_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_nFull_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_nFull_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_nFull_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_inc = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_inc = INST_top.DEF_CAN_FIRE_RL_m_cycle_inc;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_print = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_print = INST_top.DEF_CAN_FIRE_RL_m_cycle_print;
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every = INST_top.DEF_CAN_FIRE_RL_m_randomA_every;
	 INST_top.DEF_x__h24157 = INST_top.INST_m_cycle.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_init = (INST_top.DEF_x__h24157) == 0u;
	 INST_top.DEF_WILL_FIRE_RL_m_init = INST_top.DEF_CAN_FIRE_RL_m_init;
	 DEF_INST_top_DEF_m_randomC_initialized__h16928 = INST_top.INST_m_randomC_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_maybe_clear = DEF_INST_top_DEF_m_randomC_initialized__h16928;
	 INST_top.DEF_WILL_FIRE_RL_m_maybe_clear = INST_top.DEF_CAN_FIRE_RL_m_maybe_clear;
	 DEF_INST_top_DEF_m_randomA_initialized__h16152 = INST_top.INST_m_randomA_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1 = !DEF_INST_top_DEF_m_randomA_initialized__h16152;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every = INST_top.DEF_CAN_FIRE_RL_m_randomB_every;
	 DEF_INST_top_DEF_m_randomB_initialized__h16541 = INST_top.INST_m_randomB_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1 = !DEF_INST_top_DEF_m_randomB_initialized__h16541;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every = INST_top.DEF_CAN_FIRE_RL_m_randomC_every;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1 = !DEF_INST_top_DEF_m_randomC_initialized__h16928;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every = INST_top.DEF_CAN_FIRE_RL_m_randomData_every;
	 DEF_INST_top_DEF_m_randomData_initialized__h17318 = INST_top.INST_m_randomData_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1 = !DEF_INST_top_DEF_m_randomData_initialized__h17318;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_elem_count_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_elem_count_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_enq_req_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_enq_req_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_enq_req_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4;
	 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d124 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.METH_i_notEmpty();
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two = DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d124;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two;
	 INST_top.DEF_x__h24009 = INST_top.INST_m_input_count.METH_read();
	 INST_top.DEF_m_input_count_59_EQ_1024___d369 = (INST_top.DEF_x__h24009) == 1024u;
	 INST_top.DEF_CAN_FIRE_RL_m_stop_tb = INST_top.DEF_m_input_count_59_EQ_1024___d369 || (INST_top.DEF_x__h24157) == 4096u;
	 INST_top.DEF_WILL_FIRE_RL_m_stop_tb = INST_top.DEF_CAN_FIRE_RL_m_stop_tb;
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_print)
	   INST_top.RL_m_cycle_print();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full)
	   INST_top.RL_m_check_fifos_not_full();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two();
	 if (INST_top.DEF_WILL_FIRE_RL_m_stop_tb)
	   INST_top.RL_m_stop_tb();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every)
	   INST_top.RL_m_randomA_every();
	 INST_top.DEF_fifo_nFull_ehrReg__h4640 = INST_top.INST_fifo_nFull_ehrReg.METH_read();
	 INST_top.DEF_fifo_nFull_virtual_reg_2_read____d246 = INST_top.INST_fifo_nFull_virtual_reg_2.METH_read();
	 INST_top.DEF_fifo_nFull_virtual_reg_1_read____d248 = INST_top.INST_fifo_nFull_virtual_reg_1.METH_read();
	 INST_top.DEF_fifo_nFull_virtual_reg_0_read____d250 = INST_top.INST_fifo_nFull_virtual_reg_0.METH_read();
	 INST_top.DEF_def__h23669 = INST_top.INST_m_ref_fifo_elem_count_ehrReg.METH_read();
	 INST_top.DEF_x_wget__h16021 = INST_top.INST_m_randomA_zaz.METH_wget();
	 INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d238 = INST_top.INST_m_ref_fifo_elem_count_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d239 = INST_top.INST_m_ref_fifo_elem_count_virtual_reg_1.METH_read();
	 INST_top.DEF_n__read__h19919 = INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d238 || (INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d239 || INST_top.INST_m_ref_fifo_elem_count_virtual_reg_0.METH_read()) ? (tUInt8)0u : INST_top.DEF_def__h23669;
	 INST_top.DEF_v__h16158 = INST_top.INST_m_randomA_zaz.METH_whas() ? INST_top.DEF_x_wget__h16021 : (tUInt8)0u;
	 INST_top.DEF_IF_m_randomA_zaz_whas__11_THEN_m_randomA_zaz_w_ETC___d237 = (INST_top.DEF_v__h16158) == (tUInt8)0u;
	 INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d245 = !((INST_top.DEF_n__read__h19919) == (tUInt8)3u);
	 INST_top.DEF_NOT_fifo_nFull_virtual_reg_2_read__46_47_AND_N_ETC___d254 = !(INST_top.DEF_fifo_nFull_virtual_reg_2_read____d246) && (!(INST_top.DEF_fifo_nFull_virtual_reg_1_read____d248) && (!(INST_top.DEF_fifo_nFull_virtual_reg_0_read____d250) && INST_top.DEF_fifo_nFull_ehrReg__h4640));
	 INST_top.DEF_CAN_FIRE_RL_m_feed_inputs = (DEF_INST_top_DEF_m_randomA_initialized__h16152 && (INST_top.DEF_IF_m_randomA_zaz_whas__11_THEN_m_randomA_zaz_w_ETC___d237 || (INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d245 && (DEF_INST_top_DEF_m_randomData_initialized__h17318 && INST_top.DEF_NOT_fifo_nFull_virtual_reg_2_read__46_47_AND_N_ETC___d254)))) && (INST_top.DEF_x__h24009) < 1024u;
	 INST_top.DEF_WILL_FIRE_RL_m_feed_inputs = INST_top.DEF_CAN_FIRE_RL_m_feed_inputs;
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1)
	   INST_top.RL_m_randomA_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every)
	   INST_top.RL_m_randomB_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1)
	   INST_top.RL_m_randomB_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every)
	   INST_top.RL_m_randomC_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1)
	   INST_top.RL_m_randomC_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every)
	   INST_top.RL_m_randomData_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_feed_inputs)
	   INST_top.RL_m_feed_inputs();
	 INST_top.DEF_fifo_nEmpty_virtual_reg_2_read____d295 = INST_top.INST_fifo_nEmpty_virtual_reg_2.METH_read();
	 INST_top.DEF_fifo_nEmpty_virtual_reg_1_read____d297 = INST_top.INST_fifo_nEmpty_virtual_reg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_read____d301 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d117 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d118 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.METH_wget();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h9806 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_4.METH_read();
	 INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas__ETC___d120 = INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d117 ? INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d118 : INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h9806;
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d305 = INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_read____d301 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d117 ? !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d118) : !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h9806));
	 INST_top.DEF_fifo_nEmpty_wires_0_whas____d25 = INST_top.INST_fifo_nEmpty_wires_0.METH_whas();
	 INST_top.DEF_fifo_nEmpty_wires_0_wget____d26 = INST_top.INST_fifo_nEmpty_wires_0.METH_wget();
	 INST_top.DEF_fifo_nEmpty_ehrReg__h3517 = INST_top.INST_fifo_nEmpty_ehrReg.METH_read();
	 INST_top.DEF_fifo_nEmpty_virtual_reg_2_read__95_OR_fifo_nEm_ETC___d361 = INST_top.DEF_fifo_nEmpty_virtual_reg_2_read____d295 || (INST_top.DEF_fifo_nEmpty_virtual_reg_1_read____d297 || (INST_top.DEF_fifo_nEmpty_wires_0_whas____d25 ? !(INST_top.DEF_fifo_nEmpty_wires_0_wget____d26) : !(INST_top.DEF_fifo_nEmpty_ehrReg__h3517)));
	 INST_top.DEF_IF_m_ref_fifo_elem_count_wires_0_whas__57_THEN_ETC___d160 = INST_top.INST_m_ref_fifo_elem_count_wires_0.METH_whas() ? INST_top.INST_m_ref_fifo_elem_count_wires_0.METH_wget() : INST_top.DEF_def__h23669;
	 INST_top.DEF_n__read__h21647 = INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d238 || INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d239 ? (tUInt8)0u : INST_top.DEF_IF_m_ref_fifo_elem_count_wires_0_whas__57_THEN_ETC___d160;
	 INST_top.DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__3_ETC___d293 = (INST_top.DEF_n__read__h21647) == (tUInt8)0u;
	 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d306 = INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d305 || INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas__ETC___d120;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first = (INST_top.DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__3_ETC___d293 || INST_top.DEF_fifo_nEmpty_virtual_reg_2_read__95_OR_fifo_nEm_ETC___d361) || DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d306;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first && !(INST_top.DEF_WILL_FIRE_RL_m_feed_inputs);
	 INST_top.DEF_x_wget__h16410 = INST_top.INST_m_randomB_zaz.METH_wget();
	 INST_top.DEF_IF_fifo_nEmpty_wires_0_whas__5_THEN_fifo_nEmpt_ETC___d28 = INST_top.DEF_fifo_nEmpty_wires_0_whas____d25 ? INST_top.DEF_fifo_nEmpty_wires_0_wget____d26 : INST_top.DEF_fifo_nEmpty_ehrReg__h3517;
	 INST_top.DEF_v__h16547 = INST_top.INST_m_randomB_zaz.METH_whas() ? INST_top.DEF_x_wget__h16410 : (tUInt8)0u;
	 INST_top.DEF_IF_m_randomB_zaz_whas__18_THEN_m_randomB_zaz_w_ETC___d290 = (INST_top.DEF_v__h16547) == (tUInt8)0u;
	 INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d294 = !(INST_top.DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__3_ETC___d293);
	 INST_top.DEF_NOT_fifo_nEmpty_virtual_reg_2_read__95_96_AND__ETC___d300 = !(INST_top.DEF_fifo_nEmpty_virtual_reg_2_read____d295) && (!(INST_top.DEF_fifo_nEmpty_virtual_reg_1_read____d297) && INST_top.DEF_IF_fifo_nEmpty_wires_0_whas__5_THEN_fifo_nEmpt_ETC___d28);
	 INST_top.DEF_CAN_FIRE_RL_m_check_outputs = (DEF_INST_top_DEF_m_randomB_initialized__h16541 && (INST_top.DEF_IF_m_randomB_zaz_whas__18_THEN_m_randomB_zaz_w_ETC___d290 || (INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d294 && (INST_top.DEF_NOT_fifo_nEmpty_virtual_reg_2_read__95_96_AND__ETC___d300 && DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d306)))) && !(INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1);
	 INST_top.DEF_WILL_FIRE_RL_m_check_outputs = INST_top.DEF_CAN_FIRE_RL_m_check_outputs && !(INST_top.DEF_WILL_FIRE_RL_m_feed_inputs);
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty)
	   INST_top.RL_m_check_fifos_not_empty();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first)
	   INST_top.RL_m_check_fifos_first();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_outputs)
	   INST_top.RL_m_check_outputs();
	 INST_top.DEF_m_ref_fifo_enq_req_virtual_reg_2_read____d193 = INST_top.INST_m_ref_fifo_enq_req_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget____d167 = INST_top.INST_m_ref_fifo_enq_req_wires_1.METH_wget();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget____d170 = INST_top.INST_m_ref_fifo_enq_req_wires_0.METH_wget();
	 INST_top.DEF_m_ref_fifo_enq_req_ehrReg___d172 = INST_top.INST_m_ref_fifo_enq_req_ehrReg.METH_read();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_1_whas____d166 = INST_top.INST_m_ref_fifo_enq_req_wires_1.METH_whas();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_0_whas____d169 = INST_top.INST_m_ref_fifo_enq_req_wires_0.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_3__h8970 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_3.METH_read();
	 INST_top.DEF_m_ref_fifo_enq_req_ehrReg_72_BIT_8___d173 = (tUInt8)((INST_top.DEF_m_ref_fifo_enq_req_ehrReg___d172) >> 8u);
	 INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget__70_BIT_8___d171 = (tUInt8)((INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget____d170) >> 8u);
	 INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget__67_BIT_8___d168 = (tUInt8)((INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget____d167) >> 8u);
	 INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_3_whas__ETC___d113 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.METH_whas() ? INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.METH_wget() : INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_3__h8970;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize = (INST_top.DEF_m_ref_fifo_enq_req_virtual_reg_2_read____d193 || (INST_top.DEF_m_ref_fifo_enq_req_wires_1_whas____d166 ? !(INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget__67_BIT_8___d168) : (INST_top.DEF_m_ref_fifo_enq_req_wires_0_whas____d169 ? !(INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget__70_BIT_8___d171) : !(INST_top.DEF_m_ref_fifo_enq_req_ehrReg_72_BIT_8___d173)))) || (!INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_3.METH_read() && INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_3_whas__ETC___d113);
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize;
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1)
	   INST_top.RL_m_randomData_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize)
	   INST_top.RL_m_ref_fifo_canonicalize();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_read____d127 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_read____d126 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget____d48 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0.METH_wget();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget____d78 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.METH_wget();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg___d50 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1___d80 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1_read____d132 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1_read____d133 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas____d77 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_whas____d47 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_0_BIT_8___d51 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg___d50) >> 8u);
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget__8_BIT_8___d49 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget____d48) >> 8u);
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1_0_BIT_1___d81 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1___d80) >> 1u);
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget__8__ETC___d79 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget____d78) >> 1u);
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize = ((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_read____d126 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_read____d127 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_whas____d47 ? !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget__8_BIT_8___d49) : !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_0_BIT_8___d51)))) || INST_top.INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.METH_i_notFull()) && ((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1_read____d132 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1_read____d133 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas____d77 ? !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget__8__ETC___d79) : !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1_0_BIT_1___d81)))) || DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d124);
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize;
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_enq_req_canonicalize)
	   INST_top.RL_m_ref_fifo_enq_req_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_maybe_clear)
	   INST_top.RL_m_maybe_clear();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_deqPtr_canonicalize)
	   INST_top.RL_fifo_deqPtr_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_enqPtr_canonicalize)
	   INST_top.RL_fifo_enqPtr_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_nEmpty_canonicalize)
	   INST_top.RL_fifo_nEmpty_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_nFull_canonicalize)
	   INST_top.RL_fifo_nFull_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_init)
	   INST_top.RL_m_init();
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_inc)
	   INST_top.RL_m_cycle_inc();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_elem_count_canonicalize)
	   INST_top.RL_m_ref_fifo_elem_count_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1();
	 INST_top.INST_m_randomData_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomData_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nFull_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_nEmpty_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqPtr_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqPtr_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_fifo_regs_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_regs_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_regs_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_enqPtr_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_deqPtr_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_nEmpty_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_nFull_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_elem_count_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_enq_req_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_cycle.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_input_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_output_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomA_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomB_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomC_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomData_initialized.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbBypassFunctional::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbBypassFunctional_instance = new MOD_mkTbBypassFunctional(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbBypassFunctional_instance->INST_fifo_enqPtr_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqPtr_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqPtr_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqPtr_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqPtr_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqPtr_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqPtr_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqPtr_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqPtr_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqPtr_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqPtr_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqPtr_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nEmpty_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nEmpty_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nEmpty_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nEmpty_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nEmpty_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nEmpty_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nFull_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nFull_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nFull_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nFull_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nFull_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_nFull_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_2_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomA_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomA_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomB_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomB_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomC_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomC_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomData_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomData_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->set_clk_0)("CLK");
}
void MODEL_mkTbBypassFunctional::destroy_model()
{
  delete mkTbBypassFunctional_instance;
  mkTbBypassFunctional_instance = NULL;
}
void MODEL_mkTbBypassFunctional::reset_model(bool asserted)
{
  (mkTbBypassFunctional_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbBypassFunctional::get_instance()
{
  return mkTbBypassFunctional_instance;
}

/* Fill in version numbers */
void MODEL_mkTbBypassFunctional::get_version(unsigned int *year,
					     unsigned int *month,
					     char const **annotation,
					     char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "14ff62d";
}

/* Get the model creation time */
time_t MODEL_mkTbBypassFunctional::get_creation_time()
{
  
  /* Wed Jun 28 13:40:04 UTC 2023 */
  return 1687959604llu;
}

/* State dumping function */
void MODEL_mkTbBypassFunctional::dump_state()
{
  (mkTbBypassFunctional_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbBypassFunctional & mkTbBypassFunctional_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbBypassFunctional *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbBypassFunctional(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbBypassFunctional::dump_VCD_defs()
{
  (mkTbBypassFunctional_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbBypassFunctional::dump_VCD(tVCDDumpType dt)
{
  (mkTbBypassFunctional_instance->dump_VCD)(dt,
					    vcd_depth(sim_hdl),
					    mkTbBypassFunctional_backing(sim_hdl));
}
