/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Wed Jun 28 13:45:33 CST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbConflictFunctional.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbConflictFunctional::MODEL_mkTbConflictFunctional()
{
  mkTbConflictFunctional_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbConflictFunctional()
{
  MODEL_mkTbConflictFunctional *model = new MODEL_mkTbConflictFunctional();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbConflictFunctional &INST_top = *((MOD_mkTbConflictFunctional *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_m_randomA_initialized__h8493;
	 tUInt8 DEF_INST_top_DEF_m_randomB_initialized__h8882;
	 tUInt8 DEF_INST_top_DEF_m_randomData_initialized__h9659;
	 tUInt8 DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d84;
	 tUInt8 DEF_INST_top_DEF_m_randomC_initialized__h9269;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_inc = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_inc = INST_top.DEF_CAN_FIRE_RL_m_cycle_inc;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_print = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_print = INST_top.DEF_CAN_FIRE_RL_m_cycle_print;
	 INST_top.DEF_x__h11871 = INST_top.INST_m_cycle.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_init = (INST_top.DEF_x__h11871) == 0u;
	 INST_top.DEF_WILL_FIRE_RL_m_init = INST_top.DEF_CAN_FIRE_RL_m_init;
	 DEF_INST_top_DEF_m_randomC_initialized__h9269 = INST_top.INST_m_randomC_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_maybe_clear = DEF_INST_top_DEF_m_randomC_initialized__h9269;
	 INST_top.DEF_WILL_FIRE_RL_m_maybe_clear = INST_top.DEF_CAN_FIRE_RL_m_maybe_clear;
	 DEF_INST_top_DEF_m_randomA_initialized__h8493 = INST_top.INST_m_randomA_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1 = !DEF_INST_top_DEF_m_randomA_initialized__h8493;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every = INST_top.DEF_CAN_FIRE_RL_m_randomA_every;
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every = INST_top.DEF_CAN_FIRE_RL_m_randomB_every;
	 DEF_INST_top_DEF_m_randomB_initialized__h8882 = INST_top.INST_m_randomB_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1 = !DEF_INST_top_DEF_m_randomB_initialized__h8882;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every = INST_top.DEF_CAN_FIRE_RL_m_randomC_every;
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every = INST_top.DEF_CAN_FIRE_RL_m_randomData_every;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1 = !DEF_INST_top_DEF_m_randomC_initialized__h9269;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1;
	 DEF_INST_top_DEF_m_randomData_initialized__h9659 = INST_top.INST_m_randomData_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1 = !DEF_INST_top_DEF_m_randomData_initialized__h9659;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_1 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_1;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_2 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_2 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_2;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_3 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_3 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_3;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_4 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_4 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize_4;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_one = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_one = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_one;
	 DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d84 = INST_top.INST_m_ref_fifo_ref_noncf_fifo.METH_i_notEmpty();
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_two = DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d84;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_two = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_pre_canonicalize_two;
	 INST_top.DEF_x__h11723 = INST_top.INST_m_input_count.METH_read();
	 INST_top.DEF_m_input_count_52_EQ_1024___d215 = (INST_top.DEF_x__h11723) == 1024u;
	 INST_top.DEF_CAN_FIRE_RL_m_stop_tb = INST_top.DEF_m_input_count_52_EQ_1024___d215 || (INST_top.DEF_x__h11871) == 4096u;
	 INST_top.DEF_WILL_FIRE_RL_m_stop_tb = INST_top.DEF_CAN_FIRE_RL_m_stop_tb;
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_print)
	   INST_top.RL_m_cycle_print();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_one)
	   INST_top.RL_m_ref_fifo_pre_canonicalize_one();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_pre_canonicalize_two)
	   INST_top.RL_m_ref_fifo_pre_canonicalize_two();
	 if (INST_top.DEF_WILL_FIRE_RL_m_stop_tb)
	   INST_top.RL_m_stop_tb();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full)
	   INST_top.RL_m_check_fifos_not_full();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty)
	   INST_top.RL_m_check_fifos_not_empty();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first)
	   INST_top.RL_m_check_fifos_first();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every)
	   INST_top.RL_m_randomA_every();
	 INST_top.DEF_fifo_nFull__h9952 = INST_top.INST_fifo_nFull.METH_read();
	 INST_top.DEF_x_wget__h8362 = INST_top.INST_m_randomA_zaz.METH_wget();
	 INST_top.DEF_m_ref_fifo_ehrReg_3__h4648 = INST_top.INST_m_ref_fifo_ehrReg_3.METH_read();
	 INST_top.DEF_v__h8499 = INST_top.INST_m_randomA_zaz.METH_whas() ? INST_top.DEF_x_wget__h8362 : (tUInt8)0u;
	 INST_top.DEF_IF_m_ref_fifo_wires_0_3_whas__0_THEN_m_ref_fif_ETC___d73 = INST_top.INST_m_ref_fifo_wires_0_3.METH_whas() ? INST_top.INST_m_ref_fifo_wires_0_3.METH_wget() : INST_top.DEF_m_ref_fifo_ehrReg_3__h4648;
	 INST_top.DEF_IF_m_randomA_zaz_whas__17_THEN_m_randomA_zaz_w_ETC___d143 = (INST_top.DEF_v__h8499) == (tUInt8)0u;
	 INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_3_read__45_46_AND_ETC___d147 = !INST_top.INST_m_ref_fifo_virtual_reg_1_3.METH_read() && INST_top.DEF_IF_m_ref_fifo_wires_0_3_whas__0_THEN_m_ref_fif_ETC___d73;
	 INST_top.DEF_CAN_FIRE_RL_m_feed_inputs = (DEF_INST_top_DEF_m_randomA_initialized__h8493 && (INST_top.DEF_IF_m_randomA_zaz_whas__17_THEN_m_randomA_zaz_w_ETC___d143 || (DEF_INST_top_DEF_m_randomData_initialized__h9659 && (INST_top.DEF_fifo_nFull__h9952 && INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_3_read__45_46_AND_ETC___d147)))) && (INST_top.DEF_x__h11723) < 1024u;
	 INST_top.DEF_WILL_FIRE_RL_m_feed_inputs = INST_top.DEF_CAN_FIRE_RL_m_feed_inputs;
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1)
	   INST_top.RL_m_randomA_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every)
	   INST_top.RL_m_randomB_every();
	 INST_top.DEF_fifo_nEmpty__h10632 = INST_top.INST_fifo_nEmpty.METH_read();
	 INST_top.DEF_x_wget__h8751 = INST_top.INST_m_randomB_zaz.METH_wget();
	 INST_top.DEF_m_ref_fifo_ehrReg_4__h5484 = INST_top.INST_m_ref_fifo_ehrReg_4.METH_read();
	 INST_top.DEF_v__h8888 = INST_top.INST_m_randomB_zaz.METH_whas() ? INST_top.DEF_x_wget__h8751 : (tUInt8)0u;
	 INST_top.DEF_IF_m_ref_fifo_wires_0_4_whas__7_THEN_m_ref_fif_ETC___d80 = INST_top.INST_m_ref_fifo_wires_0_4.METH_whas() ? INST_top.INST_m_ref_fifo_wires_0_4.METH_wget() : INST_top.DEF_m_ref_fifo_ehrReg_4__h5484;
	 INST_top.DEF_IF_m_randomB_zaz_whas__24_THEN_m_randomB_zaz_w_ETC___d172 = (INST_top.DEF_v__h8888) == (tUInt8)0u;
	 INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_4_read__74_75_AND_ETC___d176 = !INST_top.INST_m_ref_fifo_virtual_reg_1_4.METH_read() && INST_top.DEF_IF_m_ref_fifo_wires_0_4_whas__7_THEN_m_ref_fif_ETC___d80;
	 INST_top.DEF_CAN_FIRE_RL_m_check_outputs = DEF_INST_top_DEF_m_randomB_initialized__h8882 && (INST_top.DEF_IF_m_randomB_zaz_whas__24_THEN_m_randomB_zaz_w_ETC___d172 || (INST_top.DEF_fifo_nEmpty__h10632 && INST_top.DEF_NOT_m_ref_fifo_virtual_reg_1_4_read__74_75_AND_ETC___d176));
	 INST_top.DEF_WILL_FIRE_RL_m_check_outputs = INST_top.DEF_CAN_FIRE_RL_m_check_outputs && !(INST_top.DEF_WILL_FIRE_RL_m_feed_inputs);
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_outputs)
	   INST_top.RL_m_check_outputs();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1)
	   INST_top.RL_m_randomB_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every)
	   INST_top.RL_m_randomC_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1)
	   INST_top.RL_m_randomC_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every)
	   INST_top.RL_m_randomData_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_feed_inputs)
	   INST_top.RL_m_feed_inputs();
	 INST_top.DEF_m_ref_fifo_virtual_reg_1_read____d87 = INST_top.INST_m_ref_fifo_virtual_reg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_virtual_reg_2_read____d86 = INST_top.INST_m_ref_fifo_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_wires_0_wget____d8 = INST_top.INST_m_ref_fifo_wires_0.METH_wget();
	 INST_top.DEF_m_ref_fifo_wires_0_1_wget____d38 = INST_top.INST_m_ref_fifo_wires_0_1.METH_wget();
	 INST_top.DEF_m_ref_fifo_ehrReg___d10 = INST_top.INST_m_ref_fifo_ehrReg.METH_read();
	 INST_top.DEF_m_ref_fifo_ehrReg_1___d40 = INST_top.INST_m_ref_fifo_ehrReg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_virtual_reg_2_1_read____d92 = INST_top.INST_m_ref_fifo_virtual_reg_2_1.METH_read();
	 INST_top.DEF_m_ref_fifo_virtual_reg_1_1_read____d93 = INST_top.INST_m_ref_fifo_virtual_reg_1_1.METH_read();
	 INST_top.DEF_m_ref_fifo_wires_0_1_whas____d37 = INST_top.INST_m_ref_fifo_wires_0_1.METH_whas();
	 INST_top.DEF_m_ref_fifo_wires_0_whas____d7 = INST_top.INST_m_ref_fifo_wires_0.METH_whas();
	 INST_top.DEF_m_ref_fifo_ehrReg_0_BIT_8___d11 = (tUInt8)((INST_top.DEF_m_ref_fifo_ehrReg___d10) >> 8u);
	 INST_top.DEF_m_ref_fifo_wires_0_wget_BIT_8___d9 = (tUInt8)((INST_top.DEF_m_ref_fifo_wires_0_wget____d8) >> 8u);
	 INST_top.DEF_m_ref_fifo_ehrReg_1_0_BIT_1___d41 = (tUInt8)((INST_top.DEF_m_ref_fifo_ehrReg_1___d40) >> 1u);
	 INST_top.DEF_m_ref_fifo_wires_0_1_wget__8_BIT_1___d39 = (tUInt8)((INST_top.DEF_m_ref_fifo_wires_0_1_wget____d38) >> 1u);
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_post_canonicalize = ((INST_top.DEF_m_ref_fifo_virtual_reg_2_read____d86 || (INST_top.DEF_m_ref_fifo_virtual_reg_1_read____d87 || (INST_top.DEF_m_ref_fifo_wires_0_whas____d7 ? !(INST_top.DEF_m_ref_fifo_wires_0_wget_BIT_8___d9) : !(INST_top.DEF_m_ref_fifo_ehrReg_0_BIT_8___d11)))) || INST_top.INST_m_ref_fifo_ref_noncf_fifo.METH_i_notFull()) && ((INST_top.DEF_m_ref_fifo_virtual_reg_2_1_read____d92 || (INST_top.DEF_m_ref_fifo_virtual_reg_1_1_read____d93 || (INST_top.DEF_m_ref_fifo_wires_0_1_whas____d37 ? !(INST_top.DEF_m_ref_fifo_wires_0_1_wget__8_BIT_1___d39) : !(INST_top.DEF_m_ref_fifo_ehrReg_1_0_BIT_1___d41)))) || DEF_INST_top_DEF_m_ref_fifo_ref_noncf_fifo_i_notEmpty____d84);
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_post_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_post_canonicalize;
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1)
	   INST_top.RL_m_randomData_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_2)
	   INST_top.RL_m_ref_fifo_canonicalize_2();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_3)
	   INST_top.RL_m_ref_fifo_canonicalize_3();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_4)
	   INST_top.RL_m_ref_fifo_canonicalize_4();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_post_canonicalize)
	   INST_top.RL_m_ref_fifo_post_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_maybe_clear)
	   INST_top.RL_m_maybe_clear();
	 if (INST_top.DEF_WILL_FIRE_RL_m_init)
	   INST_top.RL_m_init();
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_inc)
	   INST_top.RL_m_cycle_inc();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize)
	   INST_top.RL_m_ref_fifo_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize_1)
	   INST_top.RL_m_ref_fifo_canonicalize_1();
	 INST_top.INST_m_randomData_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomData_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_fifo_regs_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_regs_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_regs_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_enqPtr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_deqPtr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_nEmpty.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_nFull.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ref_noncf_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_ehrReg_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_cycle.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_input_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_output_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomA_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomB_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomC_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomData_initialized.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbConflictFunctional::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbConflictFunctional_instance = new MOD_mkTbConflictFunctional(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ref_noncf_fifo.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_0.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_2.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_0.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_2.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_0_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_1_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_2_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_0_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_1_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_2_1.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_0_2.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_1_2.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_0_2.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_1_2.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_0_3.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_1_3.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_0_3.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_1_3.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_0_4.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_wires_1_4.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_0_4.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_ref_fifo_ignored_wires_1_4.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomA_ignore.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomA_zaz.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomB_ignore.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomB_zaz.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomC_ignore.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomC_zaz.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomData_ignore.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->INST_m_randomData_zaz.set_clk_0)("CLK");
  (mkTbConflictFunctional_instance->set_clk_0)("CLK");
}
void MODEL_mkTbConflictFunctional::destroy_model()
{
  delete mkTbConflictFunctional_instance;
  mkTbConflictFunctional_instance = NULL;
}
void MODEL_mkTbConflictFunctional::reset_model(bool asserted)
{
  (mkTbConflictFunctional_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbConflictFunctional::get_instance()
{
  return mkTbConflictFunctional_instance;
}

/* Fill in version numbers */
void MODEL_mkTbConflictFunctional::get_version(unsigned int *year,
					       unsigned int *month,
					       char const **annotation,
					       char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "14ff62d";
}

/* Get the model creation time */
time_t MODEL_mkTbConflictFunctional::get_creation_time()
{
  
  /* Wed Jun 28 05:45:33 UTC 2023 */
  return 1687931133llu;
}

/* State dumping function */
void MODEL_mkTbConflictFunctional::dump_state()
{
  (mkTbConflictFunctional_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbConflictFunctional & mkTbConflictFunctional_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbConflictFunctional *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbConflictFunctional(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbConflictFunctional::dump_VCD_defs()
{
  (mkTbConflictFunctional_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbConflictFunctional::dump_VCD(tVCDDumpType dt)
{
  (mkTbConflictFunctional_instance->dump_VCD)(dt,
					      vcd_depth(sim_hdl),
					      mkTbConflictFunctional_backing(sim_hdl));
}
