/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sat Jul  1 22:03:18 CST 2023
 * 
 */

/* Generation options: */
#ifndef __mkFftInelasticPipeline_h__
#define __mkFftInelasticPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftInelasticPipeline module */
class MOD_mkFftInelasticPipeline : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0_0;
  MOD_mkBfly4 INST_bfly_0_1;
  MOD_mkBfly4 INST_bfly_0_10;
  MOD_mkBfly4 INST_bfly_0_11;
  MOD_mkBfly4 INST_bfly_0_12;
  MOD_mkBfly4 INST_bfly_0_13;
  MOD_mkBfly4 INST_bfly_0_14;
  MOD_mkBfly4 INST_bfly_0_15;
  MOD_mkBfly4 INST_bfly_0_2;
  MOD_mkBfly4 INST_bfly_0_3;
  MOD_mkBfly4 INST_bfly_0_4;
  MOD_mkBfly4 INST_bfly_0_5;
  MOD_mkBfly4 INST_bfly_0_6;
  MOD_mkBfly4 INST_bfly_0_7;
  MOD_mkBfly4 INST_bfly_0_8;
  MOD_mkBfly4 INST_bfly_0_9;
  MOD_mkBfly4 INST_bfly_1_0;
  MOD_mkBfly4 INST_bfly_1_1;
  MOD_mkBfly4 INST_bfly_1_10;
  MOD_mkBfly4 INST_bfly_1_11;
  MOD_mkBfly4 INST_bfly_1_12;
  MOD_mkBfly4 INST_bfly_1_13;
  MOD_mkBfly4 INST_bfly_1_14;
  MOD_mkBfly4 INST_bfly_1_15;
  MOD_mkBfly4 INST_bfly_1_2;
  MOD_mkBfly4 INST_bfly_1_3;
  MOD_mkBfly4 INST_bfly_1_4;
  MOD_mkBfly4 INST_bfly_1_5;
  MOD_mkBfly4 INST_bfly_1_6;
  MOD_mkBfly4 INST_bfly_1_7;
  MOD_mkBfly4 INST_bfly_1_8;
  MOD_mkBfly4 INST_bfly_1_9;
  MOD_mkBfly4 INST_bfly_2_0;
  MOD_mkBfly4 INST_bfly_2_1;
  MOD_mkBfly4 INST_bfly_2_10;
  MOD_mkBfly4 INST_bfly_2_11;
  MOD_mkBfly4 INST_bfly_2_12;
  MOD_mkBfly4 INST_bfly_2_13;
  MOD_mkBfly4 INST_bfly_2_14;
  MOD_mkBfly4 INST_bfly_2_15;
  MOD_mkBfly4 INST_bfly_2_2;
  MOD_mkBfly4 INST_bfly_2_3;
  MOD_mkBfly4 INST_bfly_2_4;
  MOD_mkBfly4 INST_bfly_2_5;
  MOD_mkBfly4 INST_bfly_2_6;
  MOD_mkBfly4 INST_bfly_2_7;
  MOD_mkBfly4 INST_bfly_2_8;
  MOD_mkBfly4 INST_bfly_2_9;
  MOD_Reg<tUInt32> INST_cycle;
  MOD_Reg<tUInt32> INST_fftCount;
  MOD_Reg<tUWide> INST_inElasticPipes_0;
  MOD_Reg<tUWide> INST_inElasticPipes_1;
  MOD_Reg<tUWide> INST_inElasticPipes_2;
  MOD_Fifo<tUWide> INST_inFifo;
  MOD_Fifo<tUWide> INST_outFifo;
  MOD_Reg<tUInt8> INST_valids_0;
  MOD_Reg<tUInt8> INST_valids_1;
  MOD_Reg<tUInt8> INST_valids_2;
 
 /* Constructor */
 public:
  MOD_mkFftInelasticPipeline(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_valids_1__h89737;
  tUInt8 DEF_inFifo_notEmpty____d3;
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_cycle___d7;
  tUInt32 DEF_b__h2990;
  tUWide DEF_inElasticPipes_1__h99735;
  tUWide DEF_inElasticPipes_0__h60368;
  tUWide DEF_inFifo_first____d8;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d399;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d396;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d136;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d133;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d266;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d263;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d393;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d130;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d260;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d390;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d127;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d257;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d387;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d124;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d254;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d384;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d121;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d251;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d381;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d118;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d248;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d378;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d115;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d245;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d375;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d112;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d242;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d372;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d109;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d239;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d369;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d106;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d236;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d366;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d103;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d233;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d363;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d100;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d230;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d360;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d97;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d227;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d357;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d94;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d224;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d354;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d91;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d221;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d351;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d88;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d218;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d346;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d83;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d213;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d341;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d78;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d208;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d336;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d73;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d203;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d331;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d68;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d198;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d326;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d63;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d193;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d321;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d58;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d188;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d316;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d53;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d183;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d311;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d48;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d178;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d306;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d43;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d173;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d301;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d38;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d168;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d296;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d33;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d163;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d291;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d28;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d158;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_inElasticP_ETC___d286;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d23;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_inElasticP_ETC___d153;
  tUWide DEF_deq__avValue1;
 
 /* Rules */
 public:
  void RL_counter();
  void RL_doFft();
  void RL_doFft2();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftInelasticPipeline &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftInelasticPipeline &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftInelasticPipeline &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftInelasticPipeline &backing);
};

#endif /* ifndef __mkFftInelasticPipeline_h__ */
